# Generated by Django 2.0.13 on 2019-07-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Professional_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='teacher',
            name='work_number',
            field=models.IntegerField(auto_created=True, blank=True, default=100000),
        ),
    ]
