# Generated by Django 2.0.13 on 2019-07-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190710_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='position',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
