# Generated by Django 2.0.13 on 2019-07-10 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes_name', models.CharField(max_length=20)),
                ('class_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parents_name', models.CharField(max_length=5)),
                ('user_name', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=255)),
                ('id_card', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_number', models.IntegerField(auto_created=True, blank=True, default=100000)),
                ('teacher_name', models.CharField(max_length=20)),
                ('password', models.CharField(default='', max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=11)),
                ('id_card', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=1)),
                ('position', models.CharField(max_length=20)),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_teacher', to='web.Professional')),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_classes', to='web.Professional'),
        ),
        migrations.AddField(
            model_name='classes',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t_classes', to='web.Teacher'),
        ),
    ]
